//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ2Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CQ2Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon CastleQuest2 {
            get {
                object obj = ResourceManager.GetObject("CastleQuest2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Items&gt;
        ///  &lt;Item&gt;
        ///    &lt;LongName&gt;Spider Rune&lt;/LongName&gt;
        ///    &lt;Primary&gt;45&lt;/Primary&gt;
        ///    &lt;Secondary&gt;3&lt;/Secondary&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item&gt;
        ///    &lt;LongName&gt;Viper Rune&lt;/LongName&gt;
        ///    &lt;Primary&gt;60&lt;/Primary&gt;
        ///    &lt;Secondary&gt;6&lt;/Secondary&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item&gt;
        ///    &lt;LongName&gt;Raptor Rune&lt;/LongName&gt;
        ///    &lt;Primary&gt;70&lt;/Primary&gt;
        ///    &lt;Secondary&gt;9&lt;/Secondary&gt;
        ///  &lt;/Item&gt;
        ///  &lt;Item&gt;
        ///    &lt;LongName&gt;Disciple Rune&lt;/LongName&gt;
        ///    &lt;Primary&gt;78&lt;/Primary&gt;
        ///    &lt;Secondary&gt;19&lt;/Secondary&gt;
        ///  &lt;/Ite [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
    }
}
